name: logcomex - pipelines

on:
  workflow_dispatch:
  push:
    branches:
      - 'fc/**'
      - 'feature/**'
      - 'release/**'
      - 'rc/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'main'
  pull_request:
    types: [opened, synchronize]
 
jobs:
  workflow-calling:
    uses: comexio/github-workflow-template/.github/workflows/php.yml@main
    secrets: inherit
